(()=>{'use strict';
const $=id=>document.getElementById(id);
let state=null, selected=null, currentTab='overview', signature='', lastFinding='';
const labels={pass:'Пройдено',fail:'Нарушения',incomplete:'Проверка неполная',inconclusive:'Недостаточно доказательств',not_checked:'Не проверено',running:'Выполняется',completed:'Завершено',stale:'Состояние неизвестно'};
const titles=['Административный доступ','Аутентификация','Защита соединений','Хранение данных','Защита журналов','Нормативные ссылки','Полнота аудита','Экспорт данных'];
const elem=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
function badge(status,text){return elem('span',text||labels[status]||status,'badge '+(['pass','fail','incomplete','inconclusive','critical','high','medium'].includes(status)?status:'neutral'));}
function tab(name){currentTab=name;document.querySelectorAll('[data-tab]').forEach(b=>{const on=b.dataset.tab===name;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));});document.querySelectorAll('.tab-panel').forEach(p=>p.hidden=p.id!==name);}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));
function linkFile(run,name){const a=elem('a',name);a.href='/download?run='+encodeURIComponent(run.id)+'&file='+encodeURIComponent(name);return a;}
function safeGitHub(url){try{const u=new URL(url);return u.protocol==='https:'&&u.hostname==='github.com'?u.href:null;}catch{return null;}}
function renderGitHub(){const gh=state.github;$('github').hidden=!gh;if(!gh)return;$('github-repo').textContent=gh.repository;$('github-runs').replaceChildren();if(gh.error){$('github-runs').append(elem('p',gh.error));return;}(gh.runs||[]).slice(0,4).forEach(r=>{const row=elem('div',undefined,'github-run');const a=elem('a',r.name+' · '+String(r.head_sha||'').slice(0,7));const href=safeGitHub(r.html_url);if(href){a.href=href;a.target='_blank';a.rel='noopener noreferrer';}row.append(a,badge(r.conclusion==='success'?'pass':r.conclusion==='failure'?'fail':'neutral',r.conclusion||r.status));const active=(r.steps||[]).find(s=>s.status==='in_progress');if(active)row.append(elem('small',active.name));$('github-runs').append(row);});}
function show(run){if(!run)return;selected=run.id;const report=run.report, p=run.progress||{};const terminal=run.final||run.error;const status=run.error?'incomplete':run.final?report.result:run.proposal?'neutral':p.status||'neutral';$('title').textContent=run.proposal?'Предложение исправлений':'Обзор безопасности';$('subtitle').textContent=report?'Коммит '+report.commit.slice(0,12)+' · '+report.model+' · '+run.id:run.id;$('result').replaceWith(Object.assign(badge(status,run.proposal?'Не применено':undefined),{id:'result'}));$('count').textContent=report?report.findings.length:'—';const c=report?.coverage;$('coverage').textContent=c?c.chunks_analysed+' / '+c.chunks_total:'—';$('files-count').textContent=c?c.files_indexed+' текстовых файлов · '+c.files_total+' учтено':'Исходники, настройки и документы';const seconds=report?.duration_seconds;$('duration').textContent=run.final?Math.floor(seconds/60)+'м '+Math.round(seconds%60)+'с':'—';$('usage').textContent=report?Number(report.usage.total_tokens).toLocaleString('ru-RU')+' токенов · '+report.usage.requests+' запросов':'Использование API';
const notice=run.error?.message||(run.final&&report.exit_code===2?'Проверка неполная. Наличие находок не означает завершение всех проверок.':run.proposal?'Это предложение, а не исправленный проект. Тесты и повторный аудит не выполнялись.':p.status==='stale'?p.message:'');$('notice').hidden=!notice;$('notice').textContent=notice;
const stageNames=['Сбор файлов','Анализ контекста','Проверка ИБ','Перепроверка','Отчёт'];const stageIndex={inventory:0,map:1,review:2,verify:3,snapshot:4,finished:4};let index=stageIndex[p.stage]??0;$('stages').replaceChildren();stageNames.forEach((s,i)=>{const completed=terminal?Boolean(report&&(i===0||(i===1&&c.chunks_analysed===c.chunks_total)||(i===2&&report.requirements.every(r=>r.status!=='not_checked'))||(i===3&&report.requirements.every(r=>['pass','fail'].includes(r.status)))||(i===4&&run.final))):i<index;const e=elem('div',undefined,'stage '+(completed?'done':!terminal&&i===index?'active':''));e.append(elem('i',completed?'✓':String(i+1)),elem('span',s));$('stages').append(e);});$('stage-label').textContent=terminal?'Процесс завершён':p.stage==='proposal'?'Подготовка патча':stageNames[index];$('fraction').textContent=c?c.chunks_analysed+' / '+c.chunks_total:'—';$('progress').max=c?.chunks_total||1;$('progress').value=c?.chunks_analysed||0;$('progress-message').textContent=run.final?'Результат сохранён. Полноту проверки определяют статусы требований.':p.message||'Нет событий проверки.';
$('requirements').replaceChildren();(report?.requirements||[]).forEach((r,i)=>{const tr=elem('tr');tr.append(elem('td',r.id+' · '+titles[i]));const td=elem('td');td.append(badge(r.status));tr.append(td,elem('td',String(r.finding_count)));$('requirements').append(tr);});$('downloads').replaceChildren();(run.files||[]).forEach(n=>{if(n==='dashboard.html')return;if(state.live)$('downloads').append(linkFile(run,n));else $('downloads').append(elem('span',n,'badge neutral'));});
$('findings-list').replaceChildren();for(const [key,title] of [['findings','Нарушения обязательных требований'],['additional_findings','Дополнительные записи']]){const findings=report?.[key]||[];if(!findings.length)continue;$('findings-list').append(elem('h2',title));if(key==='additional_findings')$('findings-list').append(elem('p','Дополнительные записи могут пересекаться с основными; это не число уникальных уязвимостей.','muted'));findings.forEach(f=>{const detail=elem('details',undefined,'finding');detail.append(elem('summary',f.requirement+' · '+f.title));const body=elem('div',undefined,'finding-body');const meta=elem('div',undefined,'finding-meta');meta.append(badge(f.severity,f.severity),elem('span',f.id,'muted'));body.append(meta,elem('p',f.reason),elem('p','Рекомендация: '+f.recommendation));f.evidence.forEach(e=>{body.append(elem('div',e.path+' · '+e.locator,'source-label'),elem('pre',e.snippet,'source'));});detail.append(body);$('findings-list').append(detail);});}
if(!report?.findings.length)$('findings-list').append(elem('p',run.final&&report?.exit_code===0?'Подтверждённых нарушений нет.':'Нет подтверждённых находок; проверьте полноту анализа.','empty'));
const choose=$('finding-select');lastFinding=choose.value||lastFinding;choose.replaceChildren();(report?.findings||[]).forEach(f=>{const option=elem('option',f.requirement+' · '+f.title);option.value=f.id;choose.append(option);});if([...choose.options].some(o=>o.value===lastFinding))choose.value=lastFinding;
$('propose').disabled=!state.can_propose||!run.final||!choose.value||state.proposal_busy;$('proposal-help').textContent=state.proposal_busy?'Предложение готовится. Оно появится отдельной записью в истории.':!state.can_propose?'Генерация доступна в локальной панели с указанным репозиторием и ключом DeepSeek.':'Перед запросом проверяется совпадение локального проекта с коммитом отчёта.';
$('proposal-result').replaceChildren();if(run.proposal){tab('proposal');const result=run.proposal;const block=elem('div',undefined,'panel');block.append(elem('h2',result.status==='needs_decision'?'Нужно решение разработчика':'Патч для рассмотрения'),elem('p',result.summary),elem('p','Проверено: точное совпадение замен с исходниками и синтаксис Python. Тесты не запускались.'));for(const change of result.changes||[])block.append(elem('p',change.path+' — '+change.reason));for(const risk of result.risks||[])block.append(elem('p','Ограничение: '+risk));for(const test of result.tests_to_run||[])block.append(elem('p','Рекомендуемая проверка: '+test));block.append(elem('pre',result.diff||'Изменения не предложены.','source'));if(state.live)block.append(linkFile(run,'proposal.patch'));$('proposal-result').append(block);}
}
function render(){renderGitHub();if(!state.runs.length){$('subtitle').textContent='Проверок пока нет. Запустите агент из CLI или подключите GitHub Actions.';return;}if(!state.runs.some(r=>r.id===selected))selected=state.runs[0].id;$('history').replaceChildren();state.runs.forEach(r=>{const b=elem('button',r.proposal?'Предложение патча':r.report?'Коммит '+r.report.commit.slice(0,7):r.id);b.type='button';b.classList.toggle('active',r.id===selected);b.append(elem('small',(r.proposal?r.proposal.status:labels[r.final?r.report.result:r.progress?.status]||'Диагностика')+' · '+(r.report?.started_at?new Date(r.report.started_at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}):r.id)));b.addEventListener('click',()=>{selected=r.id;signature='';render();});$('history').append(b);});show(state.runs.find(r=>r.id===selected));}
$('propose').addEventListener('click',()=>{$('paid-confirmation').hidden=false;});$('cancel-propose').addEventListener('click',()=>{$('paid-confirmation').hidden=true;});$('confirm-propose').addEventListener('click',async()=>{$('paid-confirmation').hidden=true;$('propose').disabled=true;try{const response=await fetch('/api/propose',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':state.csrf},body:JSON.stringify({run:selected,finding:$('finding-select').value,confirm_paid_request:true})});const data=await response.json();if(!response.ok)throw Error(data.error||'Не удалось запустить предложение');selected=data.run;signature='';await refresh();}catch(e){$('proposal-help').textContent=e.message;}});
async function refresh(){try{const response=await fetch('/api/state',{cache:'no-store'});if(!response.ok)throw Error('Connection');const next=await response.json();state=next;$('connection').textContent='● Подключено · обновление каждые 3 с';const nextSignature=JSON.stringify(next);if(nextSignature!==signature){signature=nextSignature;render();}}catch{$('connection').textContent='Нет связи с локальным сервером';}}
const initial=$('initial-state');if(initial){state=JSON.parse(initial.textContent);$('connection').textContent='Сохранённый отчёт · без API';render();}else{refresh();setInterval(refresh,3000);}
})();
