(()=>{'use strict';
const $=id=>document.getElementById(id);
let state=null, selected=null, currentTab='overview', signature='', lastFinding='';
const labels={pass:'Пройдено',fail:'Нарушения',incomplete:'Проверка неполная',inconclusive:'Недостаточно доказательств',not_checked:'Не проверено',running:'Выполняется',completed:'Завершено',stale:'Состояние неизвестно'};
const titles=['Административный доступ','Аутентификация','Защита соединений','Хранение данных','Защита журналов','Нормативные ссылки','Полнота аудита','Экспорт данных'];
const elem=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
function badge(status,text){return elem('span',text||labels[status]||status,'badge '+(['pass','fail','incomplete','inconclusive','critical','high','medium'].includes(status)?status:'neutral'));}
function tab(name){currentTab=name;document.querySelectorAll('[data-tab]').forEach(b=>{const on=b.dataset.tab===name;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));});document.querySelectorAll('.tab-panel').forEach(p=>p.hidden=p.id!==name);}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));
function linkFile(run,name){const a=elem('a',name);a.href='/download?run='+encodeURIComponent(run.id)+'&file='+encodeURIComponent(name);return a;}
function safeGitHub(url){try{const u=new URL(url);return u.protocol==='https:'&&u.hostname==='github.com'?u.href:null;}catch{return null;}}
function renderGitHub(){const gh=state.github;$('github').hidden=!gh;if(!gh)return;$('github-repo').textContent=gh.repository;$('github-runs').replaceChildren();if(gh.error){$('github-runs').append(elem('p',gh.error));return;}(gh.runs||[]).slice(0,4).forEach(r=>{const row=elem('div',undefined,'github-run');const a=elem('a',r.name+' · '+String(r.head_sha||'').slice(0,7));const href=safeGitHub(r.html_url);if(href){a.href=href;a.target='_blank';a.rel='noopener noreferrer';}row.append(a,badge(r.conclusion==='success'?'pass':r.conclusion==='failure'?'fail':'neutral',r.conclusion||r.status));const active=(r.steps||[]).find(s=>s.status==='in_progress');if(active)row.append(elem('small',active.name));$('github-runs').append(row);});}
function show(run){if(!run)return;selected=run.id;const report=run.report, p=run.progress||{};const terminal=run.final||run.error;const status=run.error?'incomplete':run.final?report.result:run.proposal?'neutral':p.status||'neutral';$('title').textContent=run.proposal?'Предложение исправлений':'Обзор безопасности';$('subtitle').textContent=report?'Коммит '+report.commit.slice(0,12)+' · '+report.model+' · '+run.id:run.id;$('result').replaceWith(Object.assign(badge(status,run.proposal?'Не применено':undefined),{id:'result'}));$('count').textContent=report?report.findings.length:'—';const c=report?.coverage;$('coverage').textContent=c?c.chunks_analysed+' / '+c.chunks_total:'—';$('files-count').textContent=c?c.files_indexed+' текстовых файлов · '+c.files_total+' учтено':'Исходники, настройки и документы';const seconds=report?.duration_seconds;$('duration').textContent=run.final?Math.floor(seconds/60)+'м '+Math.round(seconds%60)+'с':'—';$('usage').textContent=report?Number(report.usage.total_tokens).toLocaleString('ru-RU')+' токенов · '+report.usage.requests+' запросов':'Использование API';
const notice=(run.error?.message?friendlyError(run.error.message):'')||(run.final&&report.exit_code===2?'Проверка неполная. Наличие находок не означает завершение всех проверок.':run.proposal?'Это предложение, а не исправленный проект. Тесты и повторный аудит не выполнялись.':p.status==='stale'?p.message:'');$('notice').hidden=!notice;$('notice').textContent=notice?'Выбранный отчёт '+(report?.commit?.slice(0,7)||run.id)+': '+notice:'';
const stageNames=['Сбор файлов','Анализ контекста','Проверка ИБ','Перепроверка','Отчёт'];const stageIndex={inventory:0,map:1,review:2,verify:3,snapshot:4,finished:4};let index=stageIndex[p.stage]??0;$('stages').replaceChildren();stageNames.forEach((s,i)=>{const completed=terminal?Boolean(report&&(i===0||(i===1&&c.chunks_analysed===c.chunks_total)||(i===2&&report.requirements.every(r=>r.status!=='not_checked'))||(i===3&&report.requirements.every(r=>['pass','fail'].includes(r.status)))||(i===4&&run.final))):i<index;const e=elem('div',undefined,'stage '+(completed?'done':!terminal&&i===index?'active':''));e.append(elem('i',completed?'✓':String(i+1)),elem('span',s));$('stages').append(e);});$('stage-label').textContent=terminal?'Процесс завершён':p.stage==='proposal'?'Подготовка патча':stageNames[index];$('fraction').textContent=c?c.chunks_analysed+' / '+c.chunks_total:'—';$('progress').max=c?.chunks_total||1;$('progress').value=c?.chunks_analysed||0;$('progress-message').textContent=run.final?'Результат сохранён. Полноту проверки определяют статусы требований.':p.message||'Нет событий проверки.';
$('requirements').replaceChildren();(report?.requirements||[]).forEach((r,i)=>{const tr=elem('tr');tr.append(elem('td',r.id+' · '+titles[i]));const td=elem('td');td.append(badge(r.status));tr.append(td,elem('td',String(r.finding_count)));$('requirements').append(tr);});$('downloads').replaceChildren();(run.files||[]).forEach(n=>{if(n==='dashboard.html')return;if(state.live)$('downloads').append(linkFile(run,n));else $('downloads').append(elem('span',n,'badge neutral'));});
$('findings-list').replaceChildren();for(const [key,title] of [['findings','Нарушения обязательных требований'],['additional_findings','Дополнительные записи']]){const findings=report?.[key]||[];if(!findings.length)continue;$('findings-list').append(elem('h2',title));if(key==='additional_findings')$('findings-list').append(elem('p','Дополнительные записи могут пересекаться с основными; это не число уникальных уязвимостей.','muted'));findings.forEach(f=>{const detail=elem('details',undefined,'finding');detail.append(elem('summary',f.requirement+' · '+f.title));const body=elem('div',undefined,'finding-body');const meta=elem('div',undefined,'finding-meta');meta.append(badge(f.severity,f.severity),elem('span',f.id,'muted'));body.append(meta,elem('p',f.reason),elem('p','Рекомендация: '+f.recommendation));f.evidence.forEach(e=>{body.append(elem('div',e.path+' · '+e.locator,'source-label'),elem('pre',e.snippet,'source'));});detail.append(body);$('findings-list').append(detail);});}
if(!report?.findings.length)$('findings-list').append(elem('p',run.final&&report?.exit_code===0?'Подтверждённых нарушений нет.':'Нет подтверждённых находок; проверьте полноту анализа.','empty'));
const choose=$('finding-select');lastFinding=choose.value||lastFinding;choose.replaceChildren();(report?.findings||[]).forEach(f=>{const option=elem('option',f.requirement+' · '+f.title);option.value=f.id;choose.append(option);});if([...choose.options].some(o=>o.value===lastFinding))choose.value=lastFinding;
$('propose').disabled=!state.can_propose||!run.final||!choose.value||state.proposal_busy;$('proposal-help').textContent=state.proposal_busy?'Предложение готовится. Оно появится отдельной записью в истории.':!state.can_propose?'Генерация доступна в локальной панели с указанным репозиторием и ключом DeepSeek.':'Перед запросом проверяется совпадение локального проекта с коммитом отчёта.';
$('proposal-result').replaceChildren();if(run.proposal){tab('proposal');const result=run.proposal;const block=elem('div',undefined,'panel');block.append(elem('h2',result.status==='needs_decision'?'Нужно решение разработчика':'Патч для рассмотрения'),elem('p',result.summary),elem('p','Проверено: точное совпадение замен с исходниками и синтаксис Python. Тесты не запускались.'));for(const change of result.changes||[])block.append(elem('p',change.path+' — '+change.reason));for(const risk of result.risks||[])block.append(elem('p','Ограничение: '+risk));for(const test of result.tests_to_run||[])block.append(elem('p','Рекомендуемая проверка: '+test));block.append(elem('pre',result.diff||'Изменения не предложены.','source'));if(state.live)block.append(linkFile(run,'proposal.patch'));$('proposal-result').append(block);}
}
function render(){renderGitHub();renderActivity();if(!state.runs.length){$('subtitle').textContent='Проверок пока нет. Запустите агент из CLI или подключите GitHub Actions.';return;}if(!state.runs.some(r=>r.id===selected))selected=state.runs[0].id;$('history').replaceChildren();state.runs.forEach(r=>{const b=elem('button',r.proposal?'Предложение патча':r.report?'Коммит '+r.report.commit.slice(0,7):r.id);b.type='button';b.classList.toggle('active',r.id===selected);b.append(elem('small',(r.proposal?r.proposal.status:labels[r.final?r.report.result:r.progress?.status]||'Диагностика')+' · '+(r.report?.started_at?new Date(r.report.started_at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}):r.id)));b.addEventListener('click',()=>{selected=r.id;signature='';render();});$('history').append(b);});show(state.runs.find(r=>r.id===selected));renderActivity();}
$('propose').addEventListener('click',()=>{$('paid-confirmation').hidden=false;});$('cancel-propose').addEventListener('click',()=>{$('paid-confirmation').hidden=true;});$('confirm-propose').addEventListener('click',async()=>{$('paid-confirmation').hidden=true;$('propose').disabled=true;try{const response=await fetch('/api/propose',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':state.csrf},body:JSON.stringify({run:selected,finding:$('finding-select').value,confirm_paid_request:true})});const data=await response.json();if(!response.ok)throw Error(data.error||'Не удалось запустить предложение');selected=data.run;signature='';await refresh();}catch(e){$('proposal-help').textContent=e.message;}});
async function refresh(){try{const response=await fetch('/api/state',{cache:'no-store'});if(!response.ok)throw Error('Connection');const next=await response.json();state=next;connected=true;$('connection').textContent='● Подключено · обновление каждые 3 с';const nextSignature=JSON.stringify(next);if(nextSignature!==signature){signature=nextSignature;render();}}catch{connected=false;signature='';$('connection').textContent='Нет связи с локальным сервером';if(state)renderActivity();}}

function friendlyError(message){const match=String(message).match(/Invalid evidence range (\d+)-(\d+); file has (\d+) lines/);return match?'Модель указала строки '+match[1]+'–'+match[2]+', но в файле только '+match[3]+' строк. Проверка доказательств остановила анализ. Отчёт неполный.':message;}
let activityClock=null, connected=true;
const timeText=seconds=>{const n=Math.max(0,Math.floor(seconds));return Math.floor(n/60)+'м '+String(n%60).padStart(2,'0')+'с';};
function tickActivity(){if(!activityClock)return;const {start}=activityClock;if(activityClock.live)activityClock.end=Date.now();const seconds=(activityClock.end-start)/1000;$('activity-elapsed').textContent=Number.isFinite(seconds)?timeText(seconds):'—';if(activityClock.live)activityClock.end=Date.now();}
function activityStages(cloud,run){
if(cloud){
const groups=[['Подготовка среды',/Validate pinned|Checkout|Set up|Install trusted/],['Анализ DeepSeek',/DeepSeek full/],['Формирование отчёта',/Render dashboard/],['Сохранение результатов',/Save reports/]];
return groups.map(([name,pattern])=>{const steps=(cloud.steps||[]).filter(s=>pattern.test(s.name));let status='waiting';if(steps.some(s=>s.status==='in_progress'))status='active';else if(steps.some(s=>s.conclusion==='failure'||s.conclusion==='cancelled'))status='stopped';else if(steps.length&&steps.every(s=>s.status==='completed'&&s.conclusion==='success'))status='done';else if(steps.length&&steps.every(s=>s.status==='completed'))status='unknown';return {name,status};});
}
if(!run)return [];
const p=run.progress||{},r=run.report,c=r?.coverage;
if(run.proposal||p.stage==='proposal')return [{name:'Подготовка патча',status:run.proposal?'done':p.status==='running'?'active':'unknown'}];
const names=['Сбор файлов','Анализ контекста','Проверка требований и находок','Подготовка отчёта'];
const index={inventory:0,map:1,review:2,verify:2,snapshot:3,finished:3}[p.stage];
return names.map((name,i)=>{let status='waiting';if(run.final||run.error){const verified=r?.requirements?.length&&r.requirements.every(q=>['pass','fail'].includes(q.status));status=i===0?(c?'done':'unknown'):i===1?(c?.chunks_total&&c.chunks_analysed===c.chunks_total?'done':'unknown'):i===2?(verified?'done':'unknown'):run.final?'done':'stopped';}else if(index!==undefined){status=i<index?'done':i===index?(p.status==='running'?'active':'unknown'):'waiting';}return {name,status};});
}
function renderActivityTimeline(cloud,run,connected){
const stages=activityStages(cloud,run),active=stages.findIndex(s=>s.status==='active');
$('activity-phase').textContent=!connected?'СВЯЗЬ ПОТЕРЯНА':active>=0?'СЕЙЧАС · ЭТАП '+(active+1)+' ИЗ '+stages.length:cloud?'ОЖИДАНИЕ СОБЫТИЙ ACTIONS':run?.final||run?.error||run?.proposal?'ЗАПУСК ЗАВЕРШЁН':'ОЖИДАНИЕ СОБЫТИЙ';
$('activity-timeline').replaceChildren();
const labels={done:'Готово',active:'Сейчас',waiting:'Ожидает',unknown:'Не подтверждено',stopped:'Прервано'};
stages.forEach((stage,i)=>{const status=!connected&&stage.status==='active'?'unknown':stage.status;const row=elem('li',undefined,'timeline-step '+status);if(status==='active')row.setAttribute('aria-current','step');row.append(elem('span',status==='done'?'✓':String(i+1),'timeline-number'),elem('span',stage.name,'timeline-name'),elem('small',labels[status],'timeline-status'));$('activity-timeline').append(row);});
}
function renderActivity(){
const gh=state.github;
const cloud=(gh?.runs||[]).find(r=>r.status!=='completed'&&/security|assessment/i.test(r.name||''));
const run=state.runs.find(r=>r.id===selected)||state.runs[0];
let title='Ожидание проверки',description='Запустите проверку или отправьте изменения в подключённый репозиторий.',note='Ожидание событий.',percent=null,remaining='—',mode='idle',start=null,end=null,live=false,source='МОНИТОРИНГ АГЕНТА',percentLabel='Прогресс',remainingLabel='Осталось контекста',progressText=null,url=null;
if(cloud){
const steps=cloud.steps||[],active=steps.find(s=>s.status==='in_progress'),done=steps.filter(s=>s.status==='completed').length;
source='GITHUB ACTIONS · '+gh.repository+' · '+String(cloud.head_sha||'').slice(0,7);url=safeGitHub(cloud.html_url);
mode='running';live=true;start=cloud.run_started_at||cloud.created_at;
progressText=steps.length?done+' / '+steps.length:'—';percentLabel='Шагов Actions завершено';remaining='Неизвестно';remainingLabel='До завершения';
const name=active?.name||'';
title=cloud.status==='queued'?'Ожидание свободного runner':/DeepSeek/.test(name)?'DeepSeek проверяет проект':/Checkout/.test(name)?'Загрузка исходного кода':/Install|Python/.test(name)?'Подготовка среды проверки':/Render/.test(name)?'Формирование отчёта':/Save reports/.test(name)?'Сохранение результатов':'Выполняется GitHub Actions';
description=/DeepSeek/.test(name)?'Агент анализирует код, проверяет требования и перепроверяет находки.':active?active.name:'GitHub подготавливает задание. Ожидаем следующий шаг.';
note='GitHub передаёт текущий шаг, но не прогресс внутри DeepSeek. Поэтому процент анализа и время до завершения пока неизвестны. Обновление ≈ каждые 20 с.';
}else if(run){
const p=run.progress||{},r=run.report,c=r?.coverage,terminal=Boolean(run.final||run.error||run.proposal);
source=(run.github?'ОТЧЁТ GITHUB ACTIONS':'ЛОКАЛЬНЫЙ ЗАПУСК')+' · '+run.id;
start=r?.started_at||p.started_at;end=run.final&&r&&start?Date.parse(start)+r.duration_seconds*1000:Date.parse(p.updated_at);
live=!terminal&&p.status==='running';mode=live?'running':terminal?(run.error||r?.exit_code===2?'warning':'done'):'idle';
const names={inventory:'Сбор файлов проекта',map:'Анализ исходного кода',review:'Проверка требований безопасности',verify:'Перепроверка найденных проблем',snapshot:'Проверка неизменности исходников',proposal:'Подготовка предложения исправлений'};
title=run.error?'Проверка прервана':run.proposal?'Предложение патча готово':run.final?(r.exit_code===2?'Проверка завершилась не полностью':r.exit_code===1?'Проверка завершена: найдены нарушения':'Проверка завершена'):names[p.stage]||'Ожидание событий агента';
description=(run.error?.message?friendlyError(run.error.message):'')|| (terminal?'Результаты доступны в разделах ниже.':p.message||'Агент подготавливает анализ.');
const total=p.total||c?.chunks_total,completed=p.completed??c?.chunks_analysed;
if(total&&Number.isFinite(completed)){percent=Math.min(100,Math.floor(completed/total*100));percentLabel='Фрагментов обработано';remaining=(100-percent)+'%';}
note='Процент показывает только обработку контекста. Проверка требований и перепроверка находок выполняются отдельно. Оставшееся время неизвестно.';
if(terminal){remaining='—';note='Запуск завершён. Полнота проверки определяется статусами ИБ-01 — ИБ-08, а не процентом обработанных фрагментов.';}
if(p.status==='stale'){title='Нет свежих событий';description=p.message;note='Таймер остановлен на последнем событии. Состояние агента неизвестно.';}
}
if(gh?.error&&!cloud){mode='warning';note=gh.error;}
if(!connected){mode='warning';live=false;note='Нет связи с локальным сервером. Показаны последние полученные данные.';}
if(!state.live)live=false;
renderActivityTimeline(cloud,run,connected);$('activity').dataset.mode=mode;$('activity-source').textContent=source;$('activity-title').textContent=title;$('activity-description').textContent=description;
$('activity-percent').textContent=progressText??(percent===null?'—':percent+'%');$('activity-percent-label').textContent=percentLabel;$('activity-remaining').textContent=remaining;$('activity-remaining-label').textContent=remainingLabel;$('activity-note').textContent=note;
$('activity-progress').hidden=percent===null;$('activity-progress').value=percent||0;
$('activity-time-label').textContent=live?'Прошло времени':'Длительность / последнее событие';
$('activity-link').hidden=!url;if(url)$('activity-link').href=url;
activityClock={start:Date.parse(start),end:live?Date.now():end,live};tickActivity();
}

setInterval(tickActivity,1000);
const initial=$('initial-state');if(initial){state=JSON.parse(initial.textContent);$('connection').textContent='Сохранённый отчёт · без API';render();}else{refresh();setInterval(refresh,3000);}
})();
